repository:
  name: devshellago
  description: A flake-parts module for wrap devshell and nixago
  topics: flake-parts, nix
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
